export const FOLDER_ACTIONS = {
  ADD_FOLDER: "add-folder",
  REMOVE_FOLDER: "remove-folder",
  ADD_NOTE: "add-note",
  REMOVE_NOTE: "remove-note",
};

export const ACTIONS = {
  ADD_CHARACTER: "add-character",
  ADD_HEALTH: "add-health",
  TOGGLE_DEATH: "toggle-death",
  TOGGLE_BLIND: "toggle-blind",
  TOGGLE_CHARMED: "toggle-charmed",
  TOGGLE_DEAF: "toggle-deaf",
  TOGGLE_FRIGHTENED: "toggle-frightened",
  TOGGLE_GRAPPLE: "toggle-grapple",
  TOGGLE_INCAPACITATED: "toggle-incapacitated",
  TOGGLE_INVISIBLE: "toggle-invisible",
  TOGGLE_PARALYZED: "toggle-paralyzed",
  TOGGLE_PETRIFIED: "toggle-petrified",
  TOGGLE_POISONED: "toggle-poisoned",
  TOGGLE_PRONE: "toggle-prone",
  TOGGLE_RESTRAINED: "toggle-restrained",
  TOGGLE_STUN: "toggle-stun",
  TOGGLE_UNCONSCIOUS: "toggle-unconscious",
  TOGGLE_CONCENTRATION: "toggle-concentration",
  REMOVE_CHARACTER: "remove-character",
  NEXT_CHARACTER: "next-character",
  ADD_NOTE: "add-note",
  REMOVE_NOTE: "remove-note",
};
